//! The service layer — one module per proto service, each implementing
//! its generated Handlers trait against the shared [`crate::state::AppState`]

pub mod access_key_service;
pub mod admin_portal_service;
pub mod api_audit_log_service;
pub mod api_service;
pub mod authentication_service;
pub mod config_service;
pub mod dashboard_service;
pub mod data_access_audit_log_service;
pub mod dict_entry_service;
pub mod dict_type_service;
pub mod file_services;
pub mod internal_message_services;
pub mod language_service;
pub mod login_audit_log_service;
pub mod login_policy_service;
pub mod menu_service;
pub mod mfa_service;
pub mod monitor_services;
pub mod notification_channel_service;
pub mod online_session_service;
pub mod operation_audit_log_service;
pub mod org_unit_service;
pub mod permission_audit_log_service;
pub mod permission_group_service;
pub mod permission_service;
pub mod plan_service;
pub mod policy_evaluation_log_service;
pub mod position_service;
pub mod role_service;
pub mod script_services;
pub mod task_service;
pub mod tenant_service;
pub mod user_profile_service;
pub mod user_service;

pub use access_key_service::AccessKeyService;
pub use admin_portal_service::AdminPortalService;
pub use api_audit_log_service::ApiAuditLogService;
pub use api_service::ApiService;
pub use authentication_service::AuthenticationService;
pub use config_service::ConfigService;
pub use dashboard_service::DashboardService;
pub use data_access_audit_log_service::DataAccessAuditLogService;
pub use dict_entry_service::DictEntryService;
pub use dict_type_service::DictTypeService;
pub use file_services::{FileService, FileTransferService};
pub use internal_message_services::{
    InternalMessageCategoryService, InternalMessageRecipientService, InternalMessageService,
};
pub use language_service::LanguageService;
pub use login_audit_log_service::LoginAuditLogService;
pub use login_policy_service::LoginPolicyService;
pub use menu_service::MenuService;
pub use mfa_service::MfaService;
pub use monitor_services::{RedisCacheMonitorService, ServerMonitorService};
pub use notification_channel_service::NotificationChannelService;
pub use online_session_service::OnlineSessionService;
pub use operation_audit_log_service::OperationAuditLogService;
pub use org_unit_service::OrgUnitService;
pub use permission_audit_log_service::PermissionAuditLogService;
pub use permission_group_service::PermissionGroupService;
pub use permission_service::PermissionService;
pub use plan_service::{PlanModuleService, PlanQuotaService, PlanService};
pub use policy_evaluation_log_service::PolicyEvaluationLogService;
pub use position_service::PositionService;
pub use role_service::RoleService;
pub use script_services::{ScriptLogService, ScriptService};
pub use task_service::TaskService;
pub use tenant_service::TenantService;
pub use user_profile_service::UserProfileService;
pub use user_service::UserService;
