//! Agent downline 成交 / 分润 aggregation READ (`spec/05` §6.4 `childord` +
//! §7 三级分润树). One read answers the agent's downline earnings report: for
//! every DIRECT child (`members.parentid = agent`, `groupid != 1`), the child's
//! settled order totals and the brokerage the child accrued to *this* agent.
//!
//! The write side of §7 already landed ([`crate::ledger::profit`] credits each
//! ancestor with an `money_changes.lx = 9` flow on settle). This module only
//! READS it back. The legacy keyed those flows by `moneychange.tcuserid`
//! (the downline that generated the spread); the rewrite never modelled that
//! column, but every settle stamps the flow's `order_id` with the merchant
//! order number (`db::settle_order` → `out_order_id = order.order_id`), so the
//! per-child attribution is recovered by joining `money_changes.order_id` to
//! `orders.order_id` and scoping the order's owner (`orders.user_id`) to the
//! agent's downline — a pure read, no ledger schema change.
//!
//! Money is integer units throughout (1/10000 元), as everywhere in the
//! rewrite; the legacy `number_format(..., 2)` 元 rendering is a view concern.
//! The optional `apply_date` / `success_date` windows narrow BOTH the order
//! totals and the joined profit rows to the same period (legacy filtered the
//! orders by these and the money-change by a chained `datetime` range — we key
//! the period on the order, the shared join subject).

use std::collections::HashMap;

use sea_orm::{
    ColumnTrait, ConnectionTrait, DatabaseConnection, DbBackend, EntityTrait, QueryFilter,
    QueryOrder, Statement, Value,
};

use crate::data::members;
use crate::ledger::snapshot::lx;
use crate::state::{GatewayError, GatewayResult};

/// The report window / scope filters. `None` legs are not applied.
#[derive(Debug, Default, Clone, Copy)]
pub struct DownlineReportFilter {
    /// Restrict to a single DIRECT child (`childord` detail view); `None` =
    /// the whole downline tree (one row per child).
    pub child: Option<i64>,
    /// Inclusive `orders.apply_date` (提交时间) window, unix seconds.
    pub apply_start: Option<i64>,
    pub apply_end: Option<i64>,
    /// Inclusive `orders.success_date` (成功时间) window, unix seconds.
    pub success_start: Option<i64>,
    pub success_end: Option<i64>,
}

/// One downline child's earnings row (all money in units).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChildProfitRow {
    pub child_id: i64,
    pub username: String,
    /// `SUM(orders.amount)` over the child's `status IN (0,1,2)` orders.
    pub trade_amount: i64,
    /// `SUM(orders.poundage)` — the fees on those orders.
    pub poundage: i64,
    /// `SUM(orders.actual_amount)` — the credited arrival on those orders.
    pub actual_amount: i64,
    /// How many orders matched.
    pub order_count: i64,
    /// `SUM(money_changes.money)` of this agent's `lx = 9` brokerage flows
    /// generated by the child's orders.
    pub agent_profit: i64,
}

/// Appends `AND <col> >= $k` / `AND <col> <= $k` for whichever bounds are
/// present, bumping the placeholder counter and pushing the matching values.
fn push_range(
    sql: &mut String,
    params: &mut Vec<Value>,
    idx: &mut i64,
    col: &str,
    start: Option<i64>,
    end: Option<i64>,
) {
    if let Some(s) = start {
        *idx += 1;
        sql.push_str(&format!(" AND {col} >= ${idx}"));
        params.push(Value::from(s));
    }
    if let Some(e) = end {
        *idx += 1;
        sql.push_str(&format!(" AND {col} <= ${idx}"));
        params.push(Value::from(e));
    }
}

/// Builds the per-child ORDER TOTALS aggregate: `SELECT user_id, sum(amount),
/// sum(poundage), sum(actual_amount), count(*)` grouped by the child, over the
/// agent's downline (`parentid = $1`, `groupid != 1`) and `status IN (0,1,2)`
/// orders, within the optional windows. Exposed for offline placeholder tests.
pub(crate) fn trade_query(agent: i64, f: &DownlineReportFilter) -> (String, Vec<Value>) {
    let mut sql = String::from(
        "SELECT o.user_id, \
                cast(coalesce(sum(o.amount), 0) as bigint), \
                cast(coalesce(sum(o.poundage), 0) as bigint), \
                cast(coalesce(sum(o.actual_amount), 0) as bigint), \
                cast(count(*) as bigint) \
         FROM orders o JOIN members m ON m.id = o.user_id \
         WHERE m.parentid = $1 AND m.groupid <> 1 AND o.status IN (0, 1, 2)",
    );
    let mut params = vec![Value::from(agent)];
    let mut idx: i64 = 1;
    if let Some(c) = f.child {
        idx += 1;
        sql.push_str(&format!(" AND o.user_id = ${idx}"));
        params.push(Value::from(c));
    }
    push_range(
        &mut sql,
        &mut params,
        &mut idx,
        "o.apply_date",
        f.apply_start,
        f.apply_end,
    );
    push_range(
        &mut sql,
        &mut params,
        &mut idx,
        "o.success_date",
        f.success_start,
        f.success_end,
    );
    sql.push_str(" GROUP BY o.user_id");
    (sql, params)
}

/// Builds the per-child BROKERAGE aggregate: `SELECT o.user_id,
/// sum(mc.money)` for THIS agent's `lx = 9` flows (`mc.user_id = $1`) whose
/// order belongs to the agent's downline, within the same optional windows.
pub(crate) fn profit_query(agent: i64, f: &DownlineReportFilter) -> (String, Vec<Value>) {
    let profit = lx::PROFIT;
    let mut sql = format!(
        "SELECT o.user_id, cast(coalesce(sum(mc.money), 0) as bigint) \
         FROM money_changes mc JOIN orders o ON o.order_id = mc.order_id \
         JOIN members m ON m.id = o.user_id \
         WHERE mc.lx = {profit} AND mc.user_id = $1 AND m.parentid = $1 AND m.groupid <> 1"
    );
    let mut params = vec![Value::from(agent)];
    let mut idx: i64 = 1;
    if let Some(c) = f.child {
        idx += 1;
        sql.push_str(&format!(" AND o.user_id = ${idx}"));
        params.push(Value::from(c));
    }
    push_range(
        &mut sql,
        &mut params,
        &mut idx,
        "o.apply_date",
        f.apply_start,
        f.apply_end,
    );
    push_range(
        &mut sql,
        &mut params,
        &mut idx,
        "o.success_date",
        f.success_start,
        f.success_end,
    );
    sql.push_str(" GROUP BY o.user_id");
    (sql, params)
}

/// Runs the downline earnings report for `agent`. Children are listed first
/// (so identity + ordering survive a zero-activity child), then merged with the
/// two aggregate maps. `child = Some(x)` where `x` is not the agent's direct
/// child yields an empty report (the caller reads that as "not owned").
pub async fn downline_profit_report(
    db: &DatabaseConnection,
    agent: i64,
    f: &DownlineReportFilter,
) -> GatewayResult<Vec<ChildProfitRow>> {
    // 1. The scoped children (direct, non-platform), newest id first.
    let mut cq = members::Entity::find()
        .filter(members::Column::Parentid.eq(agent))
        .filter(members::Column::Groupid.ne(1));
    if let Some(c) = f.child {
        cq = cq.filter(members::Column::Id.eq(c));
    }
    let children = cq.order_by_desc(members::Column::Id).all(db).await?;
    if children.is_empty() {
        return Ok(Vec::new());
    }

    // 2. Order totals per child.
    let (tsql, tparams) = trade_query(agent, f);
    let trows = db
        .query_all_raw(Statement::from_sql_and_values(
            DbBackend::Postgres,
            tsql,
            tparams,
        ))
        .await
        .map_err(|e| GatewayError::Internal(format!("db: {e}")))?;
    let mut totals: HashMap<i64, (i64, i64, i64, i64)> = HashMap::new();
    for r in &trows {
        let child = r
            .try_get_by_index::<i64>(0)
            .map_err(|e| GatewayError::Internal(format!("db: {e}")))?;
        totals.insert(
            child,
            (
                r.try_get_by_index::<i64>(1).unwrap_or_default(),
                r.try_get_by_index::<i64>(2).unwrap_or_default(),
                r.try_get_by_index::<i64>(3).unwrap_or_default(),
                r.try_get_by_index::<i64>(4).unwrap_or_default(),
            ),
        );
    }

    // 3. Brokerage per child.
    let (psql, pparams) = profit_query(agent, f);
    let prows = db
        .query_all_raw(Statement::from_sql_and_values(
            DbBackend::Postgres,
            psql,
            pparams,
        ))
        .await
        .map_err(|e| GatewayError::Internal(format!("db: {e}")))?;
    let mut profit: HashMap<i64, i64> = HashMap::new();
    for r in &prows {
        let child = r
            .try_get_by_index::<i64>(0)
            .map_err(|e| GatewayError::Internal(format!("db: {e}")))?;
        profit.insert(child, r.try_get_by_index::<i64>(1).unwrap_or_default());
    }

    // 4. Merge in the children's own order.
    Ok(children
        .into_iter()
        .map(|c| {
            let (trade, poundage, actual, count) = totals.get(&c.id).copied().unwrap_or_default();
            ChildProfitRow {
                child_id: c.id,
                username: c.username,
                trade_amount: trade,
                poundage,
                actual_amount: actual,
                order_count: count,
                agent_profit: profit.get(&c.id).copied().unwrap_or_default(),
            }
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trade_query_binds_only_the_present_filters() {
        // Bare: one param ($1 = agent), status + scope present, no ranges.
        let (sql, params) = trade_query(7, &DownlineReportFilter::default());
        assert!(sql.contains("m.parentid = $1"));
        assert!(sql.contains("o.status IN (0, 1, 2)"));
        assert!(sql.ends_with("GROUP BY o.user_id"));
        assert!(!sql.contains("apply_date"));
        assert_eq!(params.len(), 1);

        // child + both windows → placeholders number up from $1.
        let f = DownlineReportFilter {
            child: Some(88),
            apply_start: Some(100),
            apply_end: Some(200),
            success_start: Some(300),
            success_end: None,
        };
        let (sql, params) = trade_query(7, &f);
        assert!(sql.contains("AND o.user_id = $2"));
        assert!(sql.contains("AND o.apply_date >= $3"));
        assert!(sql.contains("AND o.apply_date <= $4"));
        assert!(sql.contains("AND o.success_date >= $5"));
        assert!(!sql.contains("success_date <="));
        assert_eq!(params.len(), 5);
    }

    #[test]
    fn profit_query_keys_on_lx9_and_the_agent_and_joins_orders() {
        let (sql, params) = profit_query(7, &DownlineReportFilter::default());
        assert!(sql.contains(&format!("mc.lx = {}", lx::PROFIT)));
        assert!(sql.contains("mc.user_id = $1"));
        assert!(sql.contains("o.order_id = mc.order_id"));
        assert!(sql.contains("m.parentid = $1"));
        // No status predicate on the profit side (legacy keyed profit apart
        // from the order-status filter).
        assert!(!sql.contains("o.status"));
        assert_eq!(params.len(), 1);
    }
}
