//! The menu tree the boot seed plants — 34 rows over the contract's
//! navigation surface (dashboard / system / notification). Data only:
//! `seed_menus` in the parent module iterates [`ROWS`].

// Named fields over the old 9-tuple: 34 positional entries were
// one transposition away from a silent mis-seed.
#[derive(Clone, Copy)]
pub(super) struct MenuSeedRow {
    pub id: u32,
    pub parent: u32,
    pub menu_type: &'static str,
    pub path: &'static str,
    pub name: &'static str,
    pub component: &'static str,
    pub module: &'static str,
    pub title: &'static str,
    pub order: i32,
}

/// The menu tree, parent before child (the seed inserts in array order).
#[allow(clippy::all)]
pub(super) const ROWS: [MenuSeedRow; 34] = [
    MenuSeedRow {
        id: 1,
        parent: 0,
        menu_type: "CATALOG",
        path: "/dashboard",
        name: "dashboard",
        component: "dashboard",
        module: "DASHBOARD",
        title: "仪表盘",
        order: 1,
    },
    MenuSeedRow {
        id: 2,
        parent: 1,
        menu_type: "MENU",
        path: "/dashboard/console",
        name: "console",
        component: "dashboard/console/index",
        module: "DASHBOARD",
        title: "控制台",
        order: 1,
    },
    MenuSeedRow {
        id: 3,
        parent: 0,
        menu_type: "CATALOG",
        path: "/system",
        name: "system",
        component: "system",
        module: "SYSTEM",
        title: "系统管理",
        order: 2,
    },
    MenuSeedRow {
        id: 4,
        parent: 3,
        menu_type: "MENU",
        path: "/system/user",
        name: "user",
        component: "system/user/index",
        module: "SYSTEM",
        title: "用户管理",
        order: 1,
    },
    MenuSeedRow {
        id: 5,
        parent: 3,
        menu_type: "MENU",
        path: "/system/role",
        name: "role",
        component: "system/role/index",
        module: "SYSTEM",
        title: "角色管理",
        order: 2,
    },
    MenuSeedRow {
        id: 6,
        parent: 3,
        menu_type: "MENU",
        path: "/system/menu",
        name: "menu",
        component: "system/menu/index",
        module: "SYSTEM",
        title: "菜单管理",
        order: 3,
    },
    MenuSeedRow {
        id: 74,
        parent: 0,
        menu_type: "CATALOG",
        path: "/notification",
        name: "notification",
        component: "notification",
        module: "SYSTEM",
        title: "通知管理",
        order: 6,
    },
    MenuSeedRow {
        id: 68,
        parent: 74,
        menu_type: "MENU",
        path: "/notification/channels",
        name: "notification-channels",
        component: "notification/channel/index",
        module: "SYSTEM",
        title: "通知渠道",
        order: 1,
    },
    MenuSeedRow {
        id: 73,
        parent: 74,
        menu_type: "MENU",
        path: "/notification/rules",
        name: "notification-rules",
        component: "notification/rule/index",
        module: "SYSTEM",
        title: "通知规则",
        order: 2,
    },
    MenuSeedRow {
        id: 72,
        parent: 74,
        menu_type: "MENU",
        path: "/notification/deliveries",
        name: "notification-deliveries",
        component: "notification/delivery/index",
        module: "SYSTEM",
        title: "投递台账",
        order: 3,
    },
    MenuSeedRow {
        id: 10,
        parent: 3,
        menu_type: "MENU",
        path: "/system/org",
        name: "org",
        component: "system/org/index",
        module: "SYSTEM",
        title: "组织管理",
        order: 4,
    },
    MenuSeedRow {
        id: 11,
        parent: 3,
        menu_type: "MENU",
        path: "/system/position",
        name: "position",
        component: "system/position/index",
        module: "SYSTEM",
        title: "职位管理",
        order: 5,
    },
    MenuSeedRow {
        id: 20,
        parent: 3,
        menu_type: "MENU",
        path: "/system/api",
        name: "api",
        component: "system/api/index",
        module: "PERMISSION",
        title: "接口管理",
        order: 6,
    },
    MenuSeedRow {
        id: 21,
        parent: 3,
        menu_type: "MENU",
        path: "/system/permission",
        name: "permission",
        component: "system/permission/index",
        module: "PERMISSION",
        title: "权限管理",
        order: 7,
    },
    MenuSeedRow {
        id: 22,
        parent: 3,
        menu_type: "MENU",
        path: "/system/permission-group",
        name: "permissionGroup",
        component: "system/permissionGroup/index",
        module: "PERMISSION",
        title: "权限组",
        order: 8,
    },
    MenuSeedRow {
        id: 23,
        parent: 3,
        menu_type: "MENU",
        path: "/system/policy",
        name: "policy",
        component: "system/policy/index",
        module: "PERMISSION",
        title: "策略日志",
        order: 9,
    },
    MenuSeedRow {
        id: 24,
        parent: 3,
        menu_type: "MENU",
        path: "/system/permission-audit",
        name: "permissionAudit",
        component: "system/permissionAudit/index",
        module: "PERMISSION",
        title: "权限审计",
        order: 10,
    },
    MenuSeedRow {
        id: 30,
        parent: 0,
        menu_type: "CATALOG",
        path: "/dict",
        name: "dict",
        component: "dict",
        module: "DICT",
        title: "字典管理",
        order: 3,
    },
    MenuSeedRow {
        id: 31,
        parent: 30,
        menu_type: "MENU",
        path: "/dict/type",
        name: "dictType",
        component: "dict/type/index",
        module: "DICT",
        title: "字典类型",
        order: 1,
    },
    MenuSeedRow {
        id: 32,
        parent: 30,
        menu_type: "MENU",
        path: "/dict/entry",
        name: "dictEntry",
        component: "dict/entry/index",
        module: "DICT",
        title: "字典条目",
        order: 2,
    },
    MenuSeedRow {
        id: 33,
        parent: 30,
        menu_type: "MENU",
        path: "/dict/language",
        name: "language",
        component: "dict/language/index",
        module: "DICT",
        title: "语言管理",
        order: 3,
    },
    MenuSeedRow {
        id: 34,
        parent: 30,
        menu_type: "MENU",
        path: "/dict/i18n",
        name: "i18n",
        component: "dict/i18n/index",
        module: "DICT",
        title: "国际化",
        order: 4,
    },
    MenuSeedRow {
        id: 40,
        parent: 0,
        menu_type: "CATALOG",
        path: "/tenant",
        name: "tenant",
        component: "tenant",
        module: "TENANT",
        title: "租户管理",
        order: 4,
    },
    MenuSeedRow {
        id: 41,
        parent: 40,
        menu_type: "MENU",
        path: "/tenant/list",
        name: "tenantList",
        component: "tenant/list/index",
        module: "TENANT",
        title: "租户列表",
        order: 1,
    },
    MenuSeedRow {
        id: 42,
        parent: 40,
        menu_type: "MENU",
        path: "/tenant/plan",
        name: "tenantPlan",
        component: "tenant/plan/index",
        module: "TENANT",
        title: "套餐管理",
        order: 2,
    },
    MenuSeedRow {
        id: 50,
        parent: 0,
        menu_type: "CATALOG",
        path: "/log",
        name: "log",
        component: "log",
        module: "LOG",
        title: "日志管理",
        order: 5,
    },
    MenuSeedRow {
        id: 51,
        parent: 50,
        menu_type: "MENU",
        path: "/log/login",
        name: "loginLog",
        component: "log/login/index",
        module: "LOG",
        title: "登录日志",
        order: 1,
    },
    MenuSeedRow {
        id: 52,
        parent: 50,
        menu_type: "MENU",
        path: "/log/api",
        name: "apiLog",
        component: "log/api/index",
        module: "LOG",
        title: "API日志",
        order: 2,
    },
    MenuSeedRow {
        id: 53,
        parent: 50,
        menu_type: "MENU",
        path: "/log/operation",
        name: "operationLog",
        component: "log/operation/index",
        module: "LOG",
        title: "操作日志",
        order: 3,
    },
    MenuSeedRow {
        id: 54,
        parent: 50,
        menu_type: "MENU",
        path: "/log/data-access",
        name: "dataAccessLog",
        component: "log/dataAccess/index",
        module: "LOG",
        title: "数据访问日志",
        order: 4,
    },
    MenuSeedRow {
        id: 55,
        parent: 50,
        menu_type: "MENU",
        path: "/log/script",
        name: "scriptLog",
        component: "log/script/index",
        module: "LOG",
        title: "脚本日志",
        order: 5,
    },
    MenuSeedRow {
        id: 60,
        parent: 0,
        menu_type: "CATALOG",
        path: "/message",
        name: "message",
        component: "message",
        module: "INTERNAL_MESSAGE",
        title: "消息管理",
        order: 6,
    },
    MenuSeedRow {
        id: 61,
        parent: 60,
        menu_type: "MENU",
        path: "/message/list",
        name: "messageList",
        component: "message/list/index",
        module: "INTERNAL_MESSAGE",
        title: "消息列表",
        order: 1,
    },
    MenuSeedRow {
        id: 62,
        parent: 60,
        menu_type: "MENU",
        path: "/message/category",
        name: "messageCategory",
        component: "message/category/index",
        module: "INTERNAL_MESSAGE",
        title: "消息分类",
        order: 2,
    },
];
